apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "gitops.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitops.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.gitops.project }}
  
  sources:
    - repoURL: {{ .Values.gitops.repository }}
      targetRevision: {{ .Values.gitops.revision }}
      path: {{ .Values.gitops.path }}
      helm:
        values: |
          gitops:
            {{- toYaml .Values.gitops | nindent 12 }}
        valueFiles:
        {{- include "gitops.projectsPaths" . | indent 8 }}
        {{- range .Values.cluster.groups }}
        - $groups/{{ $.Values.gitops.groups.path }}/{{ . }}.yaml
        {{- end }}
        - $clusters/{{ .Values.gitops.clusters.path }}/{{ .Values.cluster.name }}.yaml
        
        ignoreMissingValueFiles: false
    - repoURL: {{ default .Values.gitops.repository .Values.gitops.clusters.repository }}
      targetRevision: {{ default .Values.gitops.revision .Values.gitops.clusters.revision }}
      ref: clusters
    - repoURL: {{ default .Values.gitops.repository .Values.gitops.groups.repository }}
      targetRevision: {{ default .Values.gitops.revision .Values.gitops.groups.revision }}
      ref: groups
    - repoURL: {{ default .Values.gitops.repository .Values.gitops.projects.repository }}
      targetRevision: {{ default .Values.gitops.revision .Values.gitops.projects.revision }}
      ref: projects

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
      
  syncPolicy:
    {{- toYaml .Values.gitops.syncPolicy | nindent 4 }}

{{ define "gitops.projectsPaths" -}}
{{ $projectList := list -}}
{{ range $_, $group := $.Values.groups -}}
{{ range $group.projects -}}
{{ if not (has . $projectList) -}}
{{ $projectList = append $projectList . -}}
{{ end -}}
{{ end -}}
{{ end -}}
{{- range $projectList }}
- $projects/{{ $.Values.gitops.projects.path }}/{{ . }}.yaml
{{- end }}
{{- end }}